// Generated by scripts/sync-constants.py from constants.py. Do not edit.
export const CONSTANTS = {
  "MULTIPLIER": {
    "10": 6.0,
    "22.5": 2.6,
    "30": 2.0,
    "45": 1.4,
    "60": 1.2
  },
  "SHRINK_PER_INCH": {
    "10": 0.0625,
    "22.5": 0.1875,
    "30": 0.25,
    "45": 0.375,
    "60": 0.5
  },
  "TAKE_UP": {
    "1/2": 5.0,
    "3/4": 6.0,
    "1": 8.0,
    "1-1/4": 11.0
  },
  "RADIUS": {
    "1/2": 4.0,
    "3/4": 5.125,
    "1": 7.0,
    "1-1/4": 8.25
  },
  "OD": {
    "1/2": 0.706,
    "3/4": 0.922,
    "1": 1.163,
    "1-1/4": 1.51
  },
  "DEFAULT_SIZE": "3/4",
  "SADDLE3_CENTER_ANGLE": 45,
  "SADDLE3_OUTER_ANGLE": 22.5,
  "SADDLE3_OUTER_FACTOR": 2.5,
  "SADDLE3_SHRINK_PER_INCH": 0.1875,
  "SADDLE4_DEFAULT_ANGLE": 22.5,
  "BENDER": {
    "model": "Greenlee 841A",
    "size": "3/4",
    "take_up": 6.0,
    "radius": 5.125,
    "marks": [
      "arrow",
      "star",
      "notch"
    ],
    "scale": [
      10,
      22.5,
      30,
      45,
      60,
      90
    ]
  },
  "HEAD": {
    "shoe_body": [
      -122.0,
      8.0
    ],
    "hook_body": 8.0,
    "hook_span": 16.0,
    "handle_body": -170.0,
    "star_body": -50.0,
    "notch_body": -25.0,
    "handle_len": 28.0,
    "hook_len": 1.0,
    "rim": 0.62,
    "scale_out": 0.18,
    "tick": 0.55,
    "pedal_body": 20.0,
    "pedal_len": 3.4,
    "rim_deep": 1.25,
    "windows": [
      [
        -104.0,
        -74.0
      ],
      [
        -58.0,
        -28.0
      ]
    ],
    "window_inset": 0.22,
    "socket_r": 1.15,
    "heel_len": 1.1,
    "pedal_wide": 2.2,
    "hook_curl": 22.0
  },
  "ANGLES": [
    10,
    22.5,
    30,
    45,
    60
  ],
  "SIZES": [
    "1/2",
    "3/4",
    "1",
    "1-1/4"
  ],
  "STICK": 120.0,
  "BUNDLE": 10,
  "COUPLING": {
    "length": 2.0,
    "engage": 1.0
  },
  "CONNECTOR_INSET": 1.0
};
